%%%-------------------------------------------------------------------
%%% File        : generic_import_directive_SUITE.erl
%%% Description : Test Suite for rule: import_directive.
%%%
%%% Created     : 01.09.2016
%%%-------------------------------------------------------------------
-module(generic_import_directive_SUITE).

-compile(export_all).

-include_lib("common_test/include/ct.hrl").
-include_lib("eunit/include/eunit.hrl").

%%--------------------------------------------------------------------
%% COMMON TEST CALLBACK FUNCTIONS - SUITE
%%--------------------------------------------------------------------

suite() ->
    [
        {timetrap, {minutes, 10}}
    ].

init_per_suite(Config) ->
    Config.

end_per_suite(_Config) ->
    ok.

%%--------------------------------------------------------------------
%% COMMON TEST CALLBACK FUNCTIONS - ALL
%%--------------------------------------------------------------------

all() ->
    [test_import_directive].

%%--------------------------------------------------------------------
%% TEST CASES
%%--------------------------------------------------------------------

test_import_directive(_Config) ->
    octest:ct_string("import (ident1 as Ident2) from \"string_1\";"),
    octest:ct_string("import \"string_2\" as _ident1;"),
    octest:ct_string("import * as _ident1from \"string_3\";"),
    octest:ct_string("import (Ident1,ident2) from \"string_2\";"),
    octest:ct_string("import (Ident1) from \"string_2\";"),
    octest:ct_string("import \"string_2\" as ident2;"),
    octest:ct_string("import Ident1 as ident2 from \"string_1\";"),
    octest:ct_string("import (ident1 as ident1) from \"string_2\";"),
    octest:ct_string("import (Ident2 as Ident2) from \"string_3\";"),
    octest:ct_string("import (Ident3 as ident1) from \"string_2\";"),
    octest:ct_string("import (ident1 as _ident2) from \"string_2\";"),
    octest:ct_string("import (_ident3 as ident2,ident1 as _ident1) from \"string_2\";"),
    octest:ct_string("import Ident2 from \"string_3\";"),
    octest:ct_string("import * as ident1from \"string_3\";"),
    octest:ct_string("import (_ident1 as Ident1) from \"string_1\";"),
    octest:ct_string("import * as Ident2from \"string_2\";"),
    octest:ct_string("import (_ident3) from \"string_3\";"),
    octest:ct_string("import (Ident3 as Ident2) from \"string_1\";"),
    octest:ct_string("import _ident1 as ident3 from \"string_3\";"),
    octest:ct_string("import * as _ident3from \"string_1\";"),
    octest:ct_string("import \"string_3\";"),
    octest:ct_string("import (_ident1,Ident2) from \"string_2\";"),
    octest:ct_string("import (Ident2 as Ident3) from \"string_3\";"),
    octest:ct_string("import * as _ident3from \"string_3\";"),
    octest:ct_string("import (Ident3,ident2) from \"string_1\";"),
    octest:ct_string("import (_ident1,_ident2) from \"string_1\";"),
    octest:ct_string("import _ident1 as _ident2 from \"string_2\";"),
    octest:ct_string("import (_ident3 as _ident2,Ident3 as ident3) from \"string_2\";"),
    octest:ct_string("import (Ident1) from \"string_3\";"),
    octest:ct_string("import (_ident3 as Ident3) from \"string_2\";"),
    octest:ct_string("import * as Ident3from \"string_3\";"),
    octest:ct_string("import * as Ident1from \"string_1\";"),
    octest:ct_string("import (Ident1 as _ident1,ident3 as _ident1) from \"string_2\";"),
    octest:ct_string("import (ident2 as ident3,_ident2 as ident3) from \"string_1\";"),
    octest:ct_string("import ident2 as Ident2 from \"string_1\";"),
    octest:ct_string("import (_ident1 as _ident3) from \"string_2\";"),
    octest:ct_string("import (Ident2,ident2) from \"string_3\";"),
    octest:ct_string("import (ident3 as Ident1) from \"string_2\";"),
    octest:ct_string("import * as Ident3from \"string_2\";"),
    octest:ct_string("import (Ident2,Ident3) from \"string_3\";"),
    octest:ct_string("import \"string_1\";"),
    octest:ct_string("import (_ident1 as Ident2,ident2 as _ident3) from \"string_3\";"),
    octest:ct_string("import (Ident3 as ident2,_ident3 as Ident2) from \"string_3\";"),
    octest:ct_string("import (Ident2,ident1) from \"string_2\";"),
    octest:ct_string("import (_ident3 as _ident3,ident1 as ident2) from \"string_3\";"),
    octest:ct_string("import (_ident1 as _ident2) from \"string_1\";"),
    octest:ct_string("import (Ident1 as Ident3,Ident1 as _ident1) from \"string_2\";"),
    octest:ct_string("import (Ident1 as ident2,ident1 as ident3) from \"string_3\";"),
    octest:ct_string("import ident1 from \"string_3\";"),
    octest:ct_string("import (Ident1,_ident2) from \"string_3\";"),
    octest:ct_string("import (_ident2,ident3) from \"string_3\";"),
    octest:ct_string("import (Ident3 as Ident2,_ident1 as _ident1) from \"string_1\";"),
    octest:ct_string("import \"string_1\" as Ident2;"),
    octest:ct_string("import (ident3 as _ident3,Ident2 as ident1) from \"string_3\";"),
    octest:ct_string("import ident2 from \"string_3\";"),
    octest:ct_string("import (_ident3 as Ident2,ident2 as ident3) from \"string_2\";"),
    octest:ct_string("import \"string_2\" as Ident2;"),
    octest:ct_string("import _ident2 as _ident2 from \"string_3\";"),
    octest:ct_string("import (_ident1,ident2) from \"string_1\";"),
    octest:ct_string("import _ident1 from \"string_1\";"),
    octest:ct_string("import (ident2 as Ident2) from \"string_2\";"),
    octest:ct_string("import ident2 as Ident3 from \"string_3\";"),
    octest:ct_string("import (ident2 as _ident2) from \"string_2\";"),
    octest:ct_string("import (ident2 as Ident1) from \"string_1\";"),
    octest:ct_string("import ident1 as ident1 from \"string_3\";"),
    octest:ct_string("import (ident2 as ident1) from \"string_2\";"),
    octest:ct_string("import (ident2 as _ident3) from \"string_3\";"),
    octest:ct_string("import (_ident2 as _ident2,_ident1 as Ident3) from \"string_3\";"),
    octest:ct_string("import ident2 as ident2 from \"string_1\";"),
    octest:ct_string("import (_ident1 as Ident3,_ident3 as Ident3) from \"string_1\";"),
    octest:ct_string("import (_ident1 as Ident3,Ident2 as ident3) from \"string_2\";"),
    octest:ct_string("import _ident3 from \"string_1\";"),
    octest:ct_string("import (Ident3,ident2) from \"string_2\";"),
    octest:ct_string("import (Ident2 as _ident3,ident2 as _ident3) from \"string_3\";"),
    octest:ct_string("import Ident3 as Ident2 from \"string_2\";"),
    octest:ct_string("import _ident3 as ident1 from \"string_1\";"),
    octest:ct_string("import Ident3 from \"string_2\";"),
    octest:ct_string("import (_ident1 as Ident2,ident2 as Ident2) from \"string_3\";"),
    octest:ct_string("import Ident1 as _ident3 from \"string_3\";"),
    octest:ct_string("import ident3 as ident1 from \"string_1\";"),
    octest:ct_string("import Ident1 as ident1 from \"string_2\";"),
    octest:ct_string("import (_ident1,Ident3) from \"string_1\";"),
    octest:ct_string("import (ident2 as _ident1,_ident2 as ident1) from \"string_2\";"),
    octest:ct_string("import (ident3 as ident1,_ident2 as ident1) from \"string_2\";"),
    octest:ct_string("import (ident2 as _ident1,_ident2 as _ident1) from \"string_3\";"),
    octest:ct_string("import (ident1 as _ident1) from \"string_2\";"),
    octest:ct_string("import ident3 from \"string_2\";"),
    octest:ct_string("import (Ident3 as _ident1,ident3 as Ident3) from \"string_1\";"),
    octest:ct_string("import (_ident1) from \"string_3\";"),
    octest:ct_string("import (Ident3 as _ident2) from \"string_2\";"),
    octest:ct_string("import (Ident2 as _ident2,ident2 as Ident1) from \"string_1\";"),
    octest:ct_string("import (Ident1 as _ident1,_ident2 as Ident3) from \"string_1\";"),
    octest:ct_string("import (Ident1,ident2) from \"string_1\";"),
    octest:ct_string("import ident2 as Ident3 from \"string_1\";"),
    octest:ct_string("import _ident1 from \"string_3\";"),
    octest:ct_string("import (_ident1 as ident3) from \"string_1\";"),
    octest:ct_string("import (_ident1,ident3) from \"string_2\";"),
    octest:ct_string("import (ident1 as _ident3,Ident3 as ident2) from \"string_3\";"),
    octest:ct_string("import (ident3 as Ident3) from \"string_3\";"),
    octest:ct_string("import * from \"string_3\";"),
    octest:ct_string("import (_ident1 as ident1,ident2 as ident2) from \"string_1\";"),
    octest:ct_string("import ident2 as ident3 from \"string_3\";"),
    octest:ct_string("import ident1 from \"string_1\";"),
    octest:ct_string("import (_ident1 as Ident2,_ident1 as _ident1) from \"string_2\";"),
    octest:ct_string("import Ident3 as _ident1 from \"string_2\";"),
    octest:ct_string("import (_ident2 as ident3) from \"string_2\";"),
    octest:ct_string("import (_ident3,ident1) from \"string_3\";"),
    octest:ct_string("import \"string_3\" as _ident1;"),
    octest:ct_string("import (ident3,ident3) from \"string_3\";"),
    octest:ct_string("import (_ident3,Ident2) from \"string_1\";"),
    octest:ct_string("import Ident1 as Ident2 from \"string_2\";"),
    octest:ct_string("import (_ident1 as _ident1,ident1 as Ident2) from \"string_2\";"),
    octest:ct_string("import Ident2 as ident2 from \"string_2\";"),
    octest:ct_string("import (Ident2 as ident3) from \"string_1\";"),
    octest:ct_string("import (Ident3) from \"string_1\";"),
    octest:ct_string("import (Ident3 as _ident2,_ident2 as _ident3) from \"string_3\";"),
    octest:ct_string("import (_ident3 as Ident1) from \"string_2\";"),
    octest:ct_string("import Ident1 as _ident3 from \"string_1\";"),
    octest:ct_string("import (ident3 as ident2) from \"string_3\";"),
    octest:ct_string("import (ident3) from \"string_2\";"),
    octest:ct_string("import (Ident1 as ident1,Ident2 as _ident1) from \"string_2\";"),
    octest:ct_string("import (_ident3 as Ident1,Ident3 as Ident3) from \"string_3\";"),
    octest:ct_string("import (_ident3 as _ident1) from \"string_3\";"),
    octest:ct_string("import (Ident3,_ident2) from \"string_2\";"),
    octest:ct_string("import (Ident1 as ident3) from \"string_1\";"),
    octest:ct_string("import (_ident2) from \"string_2\";"),
    octest:ct_string("import (_ident3 as Ident1,_ident3 as Ident3) from \"string_1\";"),
    octest:ct_string("import ident1 as Ident3 from \"string_3\";"),
    octest:ct_string("import Ident3 from \"string_3\";"),
    octest:ct_string("import (Ident3 as _ident1,_ident1 as _ident2) from \"string_2\";"),
    octest:ct_string("import (ident2) from \"string_2\";"),
    octest:ct_string("import (ident1) from \"string_3\";"),
    octest:ct_string("import (_ident2 as _ident1,ident1 as _ident1) from \"string_2\";"),
    octest:ct_string("import (_ident2) from \"string_1\";"),
    octest:ct_string("import (_ident3,ident2) from \"string_3\";"),
    octest:ct_string("import (ident2,ident2) from \"string_1\";"),
    octest:ct_string("import \"string_1\" as ident3;"),
    octest:ct_string("import Ident3 as ident3 from \"string_2\";"),
    octest:ct_string("import (ident3 as Ident1,Ident2 as ident2) from \"string_3\";"),
    octest:ct_string("import (Ident3) from \"string_2\";"),
    octest:ct_string("import (Ident2,Ident1) from \"string_3\";"),
    octest:ct_string("import (ident1 as _ident2) from \"string_1\";"),
    octest:ct_string("import _ident2 as ident2 from \"string_3\";"),
    octest:ct_string("import \"string_1\" as Ident1;"),
    octest:ct_string("import (ident2,Ident3) from \"string_2\";"),
    octest:ct_string("import * as _ident2from \"string_1\";"),
    octest:ct_string("import * as _ident1from \"string_2\";"),
    octest:ct_string("import Ident3 as ident2 from \"string_2\";"),
    octest:ct_string("import \"string_1\" as ident2;"),
    octest:ct_string("import * as Ident2from \"string_1\";"),
    octest:ct_string("import Ident3 from \"string_1\";"),
    octest:ct_string("import (ident3 as _ident1,Ident3 as Ident2) from \"string_3\";"),
    octest:ct_string("import (_ident2) from \"string_3\";"),
    octest:ct_string("import ident3 from \"string_3\";"),
    octest:ct_string("import (ident3 as ident1) from \"string_3\";"),
    octest:ct_string("import Ident3 as Ident1 from \"string_3\";"),
    octest:ct_string("import * from \"string_2\";"),
    octest:ct_string("import Ident2 from \"string_1\";"),
    octest:ct_string("import ident1 as _ident2 from \"string_1\";"),
    octest:ct_string("import ident3 as Ident1 from \"string_1\";"),
    octest:ct_string("import * as ident3from \"string_1\";"),
    octest:ct_string("import Ident3 as Ident2 from \"string_3\";"),
    octest:ct_string("import (Ident1 as _ident1) from \"string_3\";"),
    octest:ct_string("import (ident1 as ident1) from \"string_1\";"),
    octest:ct_string("import _ident3 as ident3 from \"string_3\";"),
    octest:ct_string("import (Ident3 as _ident3,ident1 as ident2) from \"string_2\";"),
    octest:ct_string("import _ident2 as ident3 from \"string_1\";"),
    octest:ct_string("import (Ident2 as ident2,Ident3 as ident1) from \"string_3\";"),
    octest:ct_string("import ident2 as _ident1 from \"string_2\";"),
    octest:ct_string("import (Ident2,ident3) from \"string_2\";"),
    octest:ct_string("import * as ident3from \"string_2\";"),
    octest:ct_string("import (_ident3,ident3) from \"string_2\";"),
    octest:ct_string("import (ident2 as _ident1,_ident3 as _ident3) from \"string_3\";"),
    octest:ct_string("import ident3 as ident1 from \"string_3\";"),
    octest:ct_string("import Ident2 as _ident2 from \"string_2\";"),
    octest:ct_string("import ident1 as ident1 from \"string_1\";"),
    octest:ct_string("import (_ident3) from \"string_1\";"),
    octest:ct_string("import _ident2 as _ident3 from \"string_3\";"),
    octest:ct_string("import (ident2) from \"string_1\";"),
    octest:ct_string("import _ident1 as ident3 from \"string_1\";"),
    octest:ct_string("import (Ident1,ident3) from \"string_1\";"),
    octest:ct_string("import (Ident3 as _ident3) from \"string_1\";"),
    octest:ct_string("import (Ident1 as _ident1) from \"string_2\";"),
    octest:ct_string("import (_ident2 as Ident2) from \"string_1\";"),
    octest:ct_string("import (Ident3 as Ident1,ident2 as ident1) from \"string_3\";"),
    octest:ct_string("import _ident2 from \"string_2\";"),
    octest:ct_string("import (Ident2 as ident1,Ident1 as Ident3) from \"string_2\";"),
    octest:ct_string("import (_ident2,ident1) from \"string_3\";"),
    octest:ct_string("import (Ident3 as _ident3,Ident1 as _ident1) from \"string_2\";"),
    octest:ct_string("import (ident1 as ident2,_ident3 as Ident1) from \"string_1\";"),
    octest:ct_string("import Ident3 as Ident3 from \"string_2\";"),
    octest:ct_string("import (ident3,ident1) from \"string_2\";"),
    octest:ct_string("import (ident1) from \"string_1\";"),
    octest:ct_string("import (Ident3 as Ident1) from \"string_2\";"),
    octest:ct_string("import (_ident3,Ident2) from \"string_3\";"),
    octest:ct_string("import _ident1 as Ident3 from \"string_2\";"),
    octest:ct_string("import (_ident3 as ident2) from \"string_2\";"),
    octest:ct_string("import (_ident3,_ident3) from \"string_1\";"),
    octest:ct_string("import Ident3 as ident1 from \"string_2\";"),
    octest:ct_string("import (ident2 as Ident3) from \"string_3\";"),
    octest:ct_string("import Ident1 from \"string_2\";"),
    octest:ct_string("import (ident2 as Ident3) from \"string_1\";"),
    octest:ct_string("import (Ident1 as ident3,Ident2 as ident2) from \"string_1\";"),
    octest:ct_string("import ident2 as ident3 from \"string_2\";"),
    octest:ct_string("import * as _ident3from \"string_2\";"),
    octest:ct_string("import * as _ident2from \"string_2\";"),
    octest:ct_string("import (Ident3 as _ident1) from \"string_3\";"),
    octest:ct_string("import _ident1 as _ident3 from \"string_3\";"),
    octest:ct_string("import \"string_3\" as _ident3;"),
    octest:ct_string("import _ident3 as ident2 from \"string_2\";"),
    octest:ct_string("import (Ident3 as ident3,_ident1 as _ident3) from \"string_1\";"),
    octest:ct_string("import (ident1,Ident3) from \"string_3\";"),
    octest:ct_string("import (Ident3,_ident3) from \"string_3\";"),
    octest:ct_string("import (_ident2 as ident3) from \"string_3\";"),
    octest:ct_string("import (ident2 as Ident3,_ident2 as ident1) from \"string_1\";"),
    octest:ct_string("import \"string_2\" as Ident1;"),
    octest:ct_string("import (ident1 as ident3) from \"string_2\";"),
    octest:ct_string("import _ident3 as ident2 from \"string_1\";"),
    octest:ct_string("import (ident3,_ident2) from \"string_3\";"),
    octest:ct_string("import ident1 as ident3 from \"string_1\";"),
    octest:ct_string("import (ident2 as _ident2) from \"string_1\";"),
    octest:ct_string("import * as _ident2from \"string_3\";"),
    octest:ct_string("import (Ident2 as _ident3,Ident3 as Ident2) from \"string_2\";"),
    octest:ct_string("import ident3 as _ident2 from \"string_1\";"),
    octest:ct_string("import ident2 as _ident1 from \"string_3\";"),
    octest:ct_string("import (Ident2 as _ident2) from \"string_1\";"),
    octest:ct_string("import (Ident1,Ident3) from \"string_3\";"),
    octest:ct_string("import _ident3 as _ident3 from \"string_3\";"),
    octest:ct_string("import (ident3) from \"string_3\";"),
    octest:ct_string("import _ident2 from \"string_3\";"),
    octest:ct_string("import (ident2) from \"string_3\";"),
    octest:ct_string("import (Ident2 as ident2,Ident3 as Ident1) from \"string_2\";"),
    octest:ct_string("import ident1 as ident3 from \"string_2\";"),
    octest:ct_string("import (Ident3 as Ident3) from \"string_2\";"),
    octest:ct_string("import Ident3 as ident1 from \"string_3\";"),
    octest:ct_string("import (_ident1,Ident1) from \"string_1\";"),
    octest:ct_string("import (_ident2 as Ident1) from \"string_3\";"),
    octest:ct_string("import (Ident2 as Ident2) from \"string_1\";"),
    octest:ct_string("import (Ident2,_ident2) from \"string_3\";"),
    octest:ct_string("import _ident1 from \"string_2\";"),
    octest:ct_string("import (Ident3,Ident2) from \"string_2\";"),
    octest:ct_string("import (Ident2) from \"string_3\";"),
    octest:ct_string("import (_ident1) from \"string_2\";"),
    octest:ct_string("import (ident1 as Ident3,_ident1 as ident2) from \"string_1\";"),
    octest:ct_string("import (Ident1,Ident1) from \"string_1\";"),
    octest:ct_string("import (ident2,Ident1) from \"string_1\";"),
    octest:ct_string("import * as Ident3from \"string_1\";"),
    octest:ct_string("import (ident2 as _ident2) from \"string_3\";"),
    octest:ct_string("import (Ident1,ident1) from \"string_3\";"),
    octest:ct_string("import (_ident1 as ident1) from \"string_2\";"),
    octest:ct_string("import (_ident2,ident2) from \"string_2\";"),
    octest:ct_string("import (_ident2,_ident1) from \"string_1\";"),
    octest:ct_string("import (ident3 as Ident2) from \"string_2\";"),
    octest:ct_string("import \"string_2\" as _ident2;"),
    octest:ct_string("import (ident3 as ident1) from \"string_2\";"),
    octest:ct_string("import (_ident1 as ident2,Ident3 as ident3) from \"string_2\";"),
    octest:ct_string("import ident3 as Ident1 from \"string_2\";"),
    octest:ct_string("import * as ident1from \"string_2\";"),
    octest:ct_string("import Ident2 as Ident2 from \"string_1\";"),
    octest:ct_string("import \"string_2\" as ident3;"),
    octest:ct_string("import (_ident3,_ident2) from \"string_2\";"),
    octest:ct_string("import (Ident1) from \"string_1\";"),
    octest:ct_string("import * as ident1from \"string_1\";"),
    octest:ct_string("import (Ident2 as ident1) from \"string_3\";"),
    octest:ct_string("import * as _ident1from \"string_1\";"),
    octest:ct_string("import (_ident1 as Ident1) from \"string_2\";"),
    octest:ct_string("import (Ident2) from \"string_2\";"),
    octest:ct_string("import _ident2 as Ident1 from \"string_3\";"),
    octest:ct_string("import ident1 as ident1 from \"string_2\";"),
    octest:ct_string("import (_ident3,_ident3) from \"string_3\";"),
    octest:ct_string("import ident2 from \"string_1\";"),
    octest:ct_string("import (_ident2 as ident2,Ident1 as ident3) from \"string_2\";"),
    octest:ct_string("import (Ident2 as Ident1) from \"string_2\";"),
    octest:ct_string("import Ident2 as ident1 from \"string_2\";"),
    octest:ct_string("import _ident1 as Ident2 from \"string_1\";"),
    octest:ct_string("import (ident3 as ident1,ident1 as _ident2) from \"string_2\";"),
    octest:ct_string("import (_ident2,ident2) from \"string_3\";"),
    octest:ct_string("import (_ident3 as Ident2) from \"string_2\";"),
    octest:ct_string("import (Ident3,_ident1) from \"string_2\";"),
    octest:ct_string("import (Ident3 as Ident1,ident3 as Ident1) from \"string_2\";"),
    octest:ct_string("import (_ident1 as ident2) from \"string_1\";"),
    octest:ct_string("import \"string_1\" as _ident2;"),
    octest:ct_string("import _ident2 as _ident1 from \"string_1\";"),
    octest:ct_string("import \"string_2\";"),
    octest:ct_string("import _ident2 as Ident1 from \"string_2\";"),
    octest:ct_string("import Ident2 from \"string_2\";"),
    octest:ct_string("import (ident2,ident1) from \"string_2\";"),
    octest:ct_string("import (_ident2 as ident2,Ident3 as Ident3) from \"string_2\";"),
    octest:ct_string("import ident1 as ident2 from \"string_1\";"),
    octest:ct_string("import (Ident1 as _ident3,Ident2 as Ident1) from \"string_1\";"),
    octest:ct_string("import Ident2 as _ident3 from \"string_2\";"),
    octest:ct_string("import (Ident1,Ident3) from \"string_2\";"),
    octest:ct_string("import (_ident1 as _ident3) from \"string_1\";"),
    octest:ct_string("import (_ident3 as _ident2) from \"string_3\";"),
    octest:ct_string("import (_ident3,ident3) from \"string_3\";"),
    octest:ct_string("import (_ident3 as Ident1,_ident2 as ident1) from \"string_2\";"),
    octest:ct_string("import \"string_2\" as Ident3;"),
    octest:ct_string("import \"string_1\" as _ident1;"),
    octest:ct_string("import (Ident3 as _ident2,ident2 as Ident2) from \"string_3\";"),
    octest:ct_string("import _ident1 as _ident1 from \"string_2\";"),
    octest:ct_string("import Ident3 as _ident3 from \"string_2\";"),
    octest:ct_string("import (ident3 as Ident1,ident2 as ident2) from \"string_2\";"),
    octest:ct_string("import _ident3 from \"string_2\";"),
    octest:ct_string("import (_ident1,_ident1) from \"string_3\";"),
    octest:ct_string("import \"string_3\" as ident2;"),
    octest:ct_string("import Ident1 as ident2 from \"string_3\";"),
    octest:ct_string("import (Ident2 as Ident2,ident2 as _ident3) from \"string_1\";"),
    octest:ct_string("import (_ident1,Ident3) from \"string_2\";"),
    octest:ct_string("import (_ident1 as ident2) from \"string_2\";"),
    octest:ct_string("import ident3 as ident2 from \"string_1\";"),
    octest:ct_string("import (Ident3) from \"string_3\";"),
    octest:ct_string("import \"string_2\" as _ident3;"),
    octest:ct_string("import Ident1 from \"string_1\";"),
    octest:ct_string("import * as Ident1from \"string_2\";"),
    octest:ct_string("import _ident2 as _ident1 from \"string_2\";"),
    octest:ct_string("import \"string_2\" as ident1;"),
    octest:ct_string("import (ident3 as Ident3,ident3 as ident3) from \"string_1\";"),
    octest:ct_string("import (ident2,Ident1) from \"string_3\";"),
    octest:ct_string("import (Ident1 as Ident1) from \"string_3\";"),
    octest:ct_string("import _ident1 as Ident2 from \"string_2\";"),
    octest:ct_string("import (ident3,Ident2) from \"string_1\";"),
    octest:ct_string("import (ident1,_ident2) from \"string_3\";"),
    octest:ct_string("import * from \"string_1\";"),
    octest:ct_string("import (ident2 as _ident3) from \"string_1\";"),
    octest:ct_string("import (ident3,Ident3) from \"string_2\";"),
    octest:ct_string("import (ident1,Ident3) from \"string_1\";"),
    octest:ct_string("import (ident3 as ident3) from \"string_3\";"),
    octest:ct_string("import (_ident1) from \"string_1\";"),
    octest:ct_string("import _ident1 as ident1 from \"string_3\";"),
    octest:ct_string("import \"string_3\" as Ident3;"),
    octest:ct_string("import (_ident3,Ident3) from \"string_1\";"),
    octest:ct_string("import (Ident2) from \"string_1\";"),
    octest:ct_string("import (_ident3,_ident2) from \"string_3\";"),
    octest:ct_string("import Ident1 as _ident1 from \"string_3\";"),
    octest:ct_string("import ident1 as _ident3 from \"string_2\";"),
    octest:ct_string("import (Ident1,_ident1) from \"string_1\";"),
    octest:ct_string("import (ident1 as Ident1) from \"string_1\";"),
    octest:ct_string("import ident3 as _ident2 from \"string_2\";"),
    octest:ct_string("import \"string_3\" as _ident2;"),
    octest:ct_string("import (_ident2,Ident3) from \"string_3\";"),
    octest:ct_string("import (Ident3 as ident2) from \"string_1\";"),
    octest:ct_string("import (ident2 as Ident2,_ident1 as _ident3) from \"string_2\";"),
    octest:ct_string("import \"string_3\" as ident3;"),
    octest:ct_string("import (_ident1 as _ident1,ident2 as _ident1) from \"string_2\";"),
    octest:ct_string("import (ident3 as _ident2,Ident1 as Ident1) from \"string_1\";"),
    octest:ct_string("import (_ident2 as Ident3) from \"string_3\";"),
    octest:ct_string("import (_ident3 as ident1) from \"string_3\";"),
    octest:ct_string("import \"string_3\" as ident1;"),
    octest:ct_string("import ident1 as ident3 from \"string_3\";"),
    octest:ct_string("import (ident2 as ident2,ident1 as Ident3) from \"string_3\";"),
    octest:ct_string("import (ident2,ident2) from \"string_2\";"),
    octest:ct_string("import (_ident3) from \"string_2\";"),
    octest:ct_string("import Ident1 as _ident3 from \"string_2\";"),
    octest:ct_string("import (Ident1 as _ident2) from \"string_2\";"),
    octest:ct_string("import (_ident1 as Ident2) from \"string_1\";"),
    octest:ct_string("import (Ident3 as _ident1,ident1 as ident1) from \"string_1\";"),
    octest:ct_string("import \"string_1\" as ident1;"),
    octest:ct_string("import Ident2 as Ident2 from \"string_2\";"),
    octest:ct_string("import ident3 as _ident1 from \"string_2\";"),
    octest:ct_string("import (Ident3 as ident2,Ident3 as Ident1) from \"string_1\";"),
    octest:ct_string("import \"string_3\" as Ident1;"),
    octest:ct_string("import Ident1 from \"string_3\";"),
    octest:ct_string("import (Ident1,ident3) from \"string_3\";"),
    octest:ct_string("import Ident1 as ident3 from \"string_3\";"),
    octest:ct_string("import (ident3 as ident2) from \"string_2\";"),
    octest:ct_string("import ident2 from \"string_2\";"),
    octest:ct_string("import (Ident1 as Ident1) from \"string_2\";"),
    octest:ct_string("import ident2 as ident1 from \"string_3\";"),
    octest:ct_string("import Ident2 as Ident3 from \"string_3\";"),
    octest:ct_string("import (ident2,Ident3) from \"string_3\";"),
    octest:ct_string("import _ident1 as ident2 from \"string_1\";"),
    octest:ct_string("import (ident3 as Ident1,ident2 as _ident3) from \"string_3\";"),
    octest:ct_string("import * as Ident1from \"string_3\";"),
    octest:ct_string("import (Ident2 as ident3,ident1 as ident2) from \"string_2\";"),
    octest:ct_string("import ident3 as ident2 from \"string_2\";"),
    octest:ct_string("import (Ident2 as ident1) from \"string_1\";"),
    octest:ct_string("import (_ident2,Ident1) from \"string_1\";"),
    octest:ct_string("import \"string_1\" as Ident3;"),
    octest:ct_string("import (ident3,_ident1) from \"string_1\";"),
    octest:ct_string("import _ident2 as Ident3 from \"string_3\";"),
    octest:ct_string("import (Ident1 as ident3) from \"string_2\";"),
    octest:ct_string("import ident1 from \"string_2\";"),
    octest:ct_string("import (ident1 as Ident3) from \"string_3\";"),
    octest:ct_string("import _ident3 as ident3 from \"string_1\";"),
    octest:ct_string("import (ident3,_ident1) from \"string_2\";"),
    octest:ct_string("import * as ident3from \"string_3\";"),
    octest:ct_string("import Ident3 as ident1 from \"string_1\";"),
    octest:ct_string("import (Ident3 as ident3,_ident3 as _ident2) from \"string_3\";"),
    octest:ct_string("import (_ident2,_ident2) from \"string_2\";"),
    octest:ct_string("import (ident2 as ident2,_ident3 as _ident2) from \"string_1\";"),
    octest:ct_string("import (Ident2 as ident2) from \"string_1\";"),
    octest:ct_string("import (ident3) from \"string_1\";"),
    octest:ct_string("import (ident2 as _ident1) from \"string_3\";"),
    octest:ct_string("import \"string_1\" as _ident3;"),
    octest:ct_string("import (ident3 as _ident3) from \"string_1\";"),
    octest:ct_string("import (ident1 as ident2,Ident3 as _ident2) from \"string_2\";"),
    octest:ct_string("import (_ident3 as ident2) from \"string_1\";"),
    octest:ct_string("import (ident3,_ident1) from \"string_3\";"),
    octest:ct_string("import (_ident3 as Ident1,ident2 as Ident2) from \"string_2\";"),
    octest:ct_string("import Ident1 as ident1 from \"string_1\";"),
    octest:ct_string("import (_ident2,Ident2) from \"string_2\";"),
    octest:ct_string("import (ident3 as Ident2,_ident1 as Ident3) from \"string_3\";"),
    octest:ct_string("import (_ident1 as ident1) from \"string_1\";"),
    octest:ct_string("import (_ident3 as Ident2,ident1 as _ident3) from \"string_1\";"),
    octest:ct_string("import (_ident3 as Ident3) from \"string_3\";"),
    octest:ct_string("import (_ident3 as _ident3,Ident1 as Ident3) from \"string_2\";"),
    octest:ct_string("import _ident2 from \"string_1\";"),
    octest:ct_string("import (Ident2 as _ident1,Ident1 as ident3) from \"string_1\";"),
    octest:ct_string("import * as ident2from \"string_3\";"),
    octest:ct_string("import ident2 as Ident1 from \"string_2\";"),
    octest:ct_string("import _ident3 from \"string_3\";"),
    octest:ct_string("import (_ident1,Ident2) from \"string_3\";"),
    octest:ct_string("import _ident2 as ident1 from \"string_3\";"),
    octest:ct_string("import (ident1) from \"string_2\";"),
    octest:ct_string("import (Ident2,ident3) from \"string_1\";"),
    octest:ct_string("import (_ident2,_ident2) from \"string_1\";"),
    octest:ct_string("import * as ident2from \"string_1\";"),
    octest:ct_string("import (_ident3 as _ident3,Ident2 as Ident2) from \"string_3\";"),
    octest:ct_string("import (_ident3,_ident3) from \"string_2\";"),
    octest:ct_string("import (ident1,Ident2) from \"string_2\";"),
    octest:ct_string("import (Ident3 as Ident2,ident2 as Ident1) from \"string_3\";"),
    octest:ct_string("import (_ident2 as _ident2,Ident3 as ident1) from \"string_3\";"),
    octest:ct_string("import (ident2,_ident1) from \"string_3\";"),
    octest:ct_string("import (ident3,ident2) from \"string_3\";"),
    octest:ct_string("import (Ident3,_ident2) from \"string_3\";"),
    octest:ct_string("import (Ident1 as _ident3,Ident1 as Ident1) from \"string_2\";"),
    octest:ct_string("import ident3 from \"string_1\";"),
    octest:ct_string("import (_ident1 as ident1) from \"string_3\";"),
    octest:ct_string("import (Ident3,ident3) from \"string_3\";"),
    octest:ct_string("import \"string_3\" as Ident2;"),
    octest:ct_string("import (_ident2 as ident1) from \"string_3\";"),
    octest:ct_string("import (ident1,ident3) from \"string_3\";"),
    octest:ct_string("import (ident2 as _ident1,_ident3 as Ident1) from \"string_2\";"),
    octest:ct_string("import (_ident2,Ident2) from \"string_3\";"),
    octest:ct_string("import * as Ident2from \"string_3\";").
